const { db } = require('../config/firebase');
require('dotenv').config();

const libraries = [
  // FRONTEND FRAMEWORKS (15)
  {
    name: 'React',
    description: 'A JavaScript library for building user interfaces',
    category: 'Frontend',
    version: '18.2.0',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 220000,
    downloads: 18500000,
    rating: 4.9,
    reviews_count: 15420,
    homepage: 'https://reactjs.org',
    repository: 'https://github.com/facebook/react',
    documentation: 'https://react.dev',
    dependencies: [],
    tags: ['javascript', 'ui', 'library', 'components'],
    codeExample: `import React from 'react';\n\nfunction App() {\n  return <h1>Hello World</h1>;\n}\n\nexport default App;`
  },
  {
    name: 'Vue.js',
    description: 'The Progressive JavaScript Framework',
    category: 'Frontend',
    version: '3.3.4',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 207000,
    downloads: 9200000,
    rating: 4.8,
    reviews_count: 12350,
    homepage: 'https://vuejs.org',
    repository: 'https://github.com/vuejs/vue',
    documentation: 'https://vuejs.org/guide/',
    dependencies: [],
    tags: ['javascript', 'framework', 'reactive'],
    codeExample: `import { createApp } from 'vue';\n\nconst app = createApp({\n  data() {\n    return { message: 'Hello Vue!' }\n  }\n});\n\napp.mount('#app');`
  },
  {
    name: 'Angular',
    description: 'Platform for building mobile and desktop web applications',
    category: 'Frontend',
    version: '16.2.0',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 95000,
    downloads: 3100000,
    rating: 4.6,
    reviews_count: 8950,
    homepage: 'https://angular.io',
    repository: 'https://github.com/angular/angular',
    documentation: 'https://angular.io/docs',
    dependencies: ['rxjs', 'zone.js'],
    tags: ['typescript', 'framework', 'spa'],
    codeExample: `import { Component } from '@angular/core';\n\n@Component({\n  selector: 'app-root',\n  template: '<h1>{{ title }}</h1>'\n})\nexport class AppComponent {\n  title = 'Hello Angular';\n}`
  },
  {
    name: 'Svelte',
    description: 'Cybernetically enhanced web apps',
    category: 'Frontend',
    version: '4.2.0',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 75000,
    downloads: 1800000,
    rating: 4.9,
    reviews_count: 5230,
    homepage: 'https://svelte.dev',
    repository: 'https://github.com/sveltejs/svelte',
    documentation: 'https://svelte.dev/docs',
    dependencies: [],
    tags: ['javascript', 'compiler', 'reactive'],
    codeExample: `<script>\n  let count = 0;\n</script>\n\n<button on:click={() => count++}>\n  Clicked {count} times\n</button>`
  },
  {
    name: 'Next.js',
    description: 'The React Framework for Production',
    category: 'Frontend',
    version: '14.0.0',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 120000,
    downloads: 5800000,
    rating: 4.8,
    reviews_count: 9870,
    homepage: 'https://nextjs.org',
    repository: 'https://github.com/vercel/next.js',
    documentation: 'https://nextjs.org/docs',
    dependencies: ['react', 'react-dom'],
    tags: ['react', 'ssr', 'framework'],
    codeExample: `export default function Page() {\n  return <h1>Hello from Next.js!</h1>;\n}`
  },
  {
    name: 'jQuery',
    description: 'Fast, small, and feature-rich JavaScript library',
    category: 'Frontend',
    version: '3.7.1',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 59000,
    downloads: 8900000,
    rating: 4.5,
    reviews_count: 18750,
    homepage: 'https://jquery.com',
    repository: 'https://github.com/jquery/jquery',
    documentation: 'https://api.jquery.com',
    dependencies: [],
    tags: ['javascript', 'dom', 'ajax'],
    codeExample: `$('#myButton').click(function() {\n  $('#myDiv').hide();\n});`
  },
  {
    name: 'Ember.js',
    description: 'A framework for ambitious web developers',
    category: 'Frontend',
    version: '5.4.0',
    platforms: ['windows', 'macos'],
    license: 'MIT',
    cost: 'Free',
    stars: 22000,
    downloads: 580000,
    rating: 4.4,
    reviews_count: 2150,
    homepage: 'https://emberjs.com',
    repository: 'https://github.com/emberjs/ember.js',
    documentation: 'https://guides.emberjs.com',
    dependencies: [],
    tags: ['javascript', 'framework', 'mvc'],
    codeExample: `import Component from '@glimmer/component';\n\nexport default class HelloComponent extends Component {\n  get message() {\n    return 'Hello Ember!';\n  }\n}`
  },
  {
    name: 'Preact',
    description: 'Fast 3kB alternative to React with the same modern API',
    category: 'Frontend',
    version: '10.18.1',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 36000,
    downloads: 2100000,
    rating: 4.7,
    reviews_count: 3420,
    homepage: 'https://preactjs.com',
    repository: 'https://github.com/preactjs/preact',
    documentation: 'https://preactjs.com/guide/v10/getting-started',
    dependencies: [],
    tags: ['javascript', 'lightweight', 'react-alternative'],
    codeExample: `import { render } from 'preact';\n\nfunction App() {\n  return <h1>Hello Preact!</h1>;\n}\n\nrender(<App />, document.body);`
  },
  {
    name: 'Alpine.js',
    description: 'A rugged, minimal framework for composing JavaScript behavior',
    category: 'Frontend',
    version: '3.13.0',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 27000,
    downloads: 950000,
    rating: 4.6,
    reviews_count: 2890,
    homepage: 'https://alpinejs.dev',
    repository: 'https://github.com/alpinejs/alpine',
    documentation: 'https://alpinejs.dev/start-here',
    dependencies: [],
    tags: ['javascript', 'lightweight', 'reactive'],
    codeExample: `<div x-data="{ count: 0 }">\n  <button @click="count++">Increment</button>\n  <span x-text="count"></span>\n</div>`
  },
  {
    name: 'Solid.js',
    description: 'Simple and performant reactivity for building user interfaces',
    category: 'Frontend',
    version: '1.7.11',
    platforms: ['windows', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 29000,
    downloads: 900000,
    rating: 4.8,
    reviews_count: 2340,
    homepage: 'https://www.solidjs.com',
    repository: 'https://github.com/solidjs/solid',
    documentation: 'https://www.solidjs.com/docs/latest',
    dependencies: [],
    tags: ['javascript', 'reactive', 'performant'],
    codeExample: `import { createSignal } from 'solid-js';\n\nfunction Counter() {\n  const [count, setCount] = createSignal(0);\n  return <button onClick={() => setCount(count() + 1)}>{count()}</button>;\n}`
  },
  {
    name: 'Lit',
    description: 'Simple. Fast. Web Components.',
    category: 'Frontend',
    version: '3.0.0',
    platforms: ['windows', 'macos', 'linux'],
    license: 'BSD-3-Clause',
    cost: 'Free',
    stars: 17000,
    downloads: 4200000,
    rating: 4.5,
    reviews_count: 1890,
    homepage: 'https://lit.dev',
    repository: 'https://github.com/lit/lit',
    documentation: 'https://lit.dev/docs/',
    dependencies: [],
    tags: ['web-components', 'javascript', 'polymer'],
    codeExample: `import { LitElement, html } from 'lit';\n\nclass MyElement extends LitElement {\n  render() {\n    return html\`<p>Hello from Lit!</p>\`;\n  }\n}\ncustomElements.define('my-element', MyElement);`
  },
  {
    name: 'Stimulus',
    description: 'A modest JavaScript framework for the HTML you already have',
    category: 'Frontend',
    version: '3.2.2',
    platforms: ['windows', 'macos'],
    license: 'MIT',
    cost: 'Free',
    stars: 12000,
    downloads: 780000,
    rating: 4.3,
    reviews_count: 980,
    homepage: 'https://stimulus.hotwired.dev',
    repository: 'https://github.com/hotwired/stimulus',
    documentation: 'https://stimulus.hotwired.dev/handbook/introduction',
    dependencies: [],
    tags: ['javascript', 'hotwire', 'progressive-enhancement'],
    codeExample: `import { Controller } from "@hotwired/stimulus"\n\nexport default class extends Controller {\n  connect() {\n    this.element.textContent = "Hello Stimulus!"\n  }\n}`
  },
  {
    name: 'Mithril',
    description: 'A modern client-side JavaScript framework',
    category: 'Frontend',
    version: '2.2.2',
    platforms: ['linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 14000,
    downloads: 120000,
    rating: 4.2,
    reviews_count: 670,
    homepage: 'https://mithril.js.org',
    repository: 'https://github.com/MithrilJS/mithril.js',
    documentation: 'https://mithril.js.org/index.html',
    dependencies: [],
    tags: ['javascript', 'framework', 'lightweight'],
    codeExample: `var m = require("mithril");\n\nvar Hello = {\n  view: function() {\n    return m("h1", "Hello Mithril");\n  }\n};\n\nm.mount(document.body, Hello);`
  },
  {
    name: 'Qwik',
    description: 'The HTML-first framework. Instant apps of any size with ~ 1kb JS',
    category: 'Frontend',
    version: '1.2.12',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 20000,
    downloads: 290000,
    rating: 4.7,
    reviews_count: 1450,
    homepage: 'https://qwik.builder.io',
    repository: 'https://github.com/BuilderIO/qwik',
    documentation: 'https://qwik.builder.io/docs/',
    dependencies: [],
    tags: ['javascript', 'resumable', 'fast'],
    codeExample: `import { component$ } from '@builder.io/qwik';\n\nexport default component$(() => {\n  return <h1>Hello Qwik!</h1>;\n});`
  },
  {
    name: 'Nuxt.js',
    description: 'The Intuitive Vue Framework',
    category: 'Frontend',
    version: '3.8.0',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 51000,
    downloads: 1900000,
    rating: 4.7,
    reviews_count: 6780,
    homepage: 'https://nuxt.com',
    repository: 'https://github.com/nuxt/nuxt',
    documentation: 'https://nuxt.com/docs',
    dependencies: ['vue'],
    tags: ['vue', 'ssr', 'framework'],
    codeExample: `<template>\n  <div>\n    <h1>{{ message }}</h1>\n  </div>\n</template>\n\n<script setup>\nconst message = 'Hello Nuxt!'\n</script>`
  },

  // CSS FRAMEWORKS (10)
  {
    name: 'Bootstrap',
    description: 'The most popular HTML, CSS, and JS library',
    category: 'CSS Framework',
    version: '5.3.0',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 168000,
    downloads: 8800000,
    rating: 4.7,
    reviews_count: 22150,
    homepage: 'https://getbootstrap.com',
    repository: 'https://github.com/twbs/bootstrap',
    documentation: 'https://getbootstrap.com/docs/',
    dependencies: [],
    tags: ['css', 'responsive', 'components'],
    codeExample: `<button class="btn btn-primary">Click me</button>`
  },
  {
    name: 'Tailwind CSS',
    description: 'A utility-first CSS framework',
    category: 'CSS Framework',
    version: '3.3.5',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 78000,
    downloads: 12500000,
    rating: 4.9,
    reviews_count: 18950,
    homepage: 'https://tailwindcss.com',
    repository: 'https://github.com/tailwindlabs/tailwindcss',
    documentation: 'https://tailwindcss.com/docs',
    dependencies: [],
    tags: ['css', 'utility-first', 'customizable'],
    codeExample: `<button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">\n  Button\n</button>`
  },
  {
    name: 'Material-UI',
    description: 'React components for faster and easier web development',
    category: 'CSS Framework',
    version: '5.14.15',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 92000,
    downloads: 3500000,
    rating: 4.6,
    reviews_count: 9230,
    homepage: 'https://mui.com',
    repository: 'https://github.com/mui/material-ui',
    documentation: 'https://mui.com/material-ui/getting-started/',
    dependencies: ['react', 'react-dom'],
    tags: ['react', 'material-design', 'components'],
    codeExample: `import Button from '@mui/material/Button';\n\nfunction App() {\n  return <Button variant="contained">Hello World</Button>;\n}`
  },
  {
    name: 'Bulma',
    description: 'Modern CSS framework based on Flexbox',
    category: 'CSS Framework',
    version: '0.9.4',
    platforms: ['windows', 'macos'],
    license: 'MIT',
    cost: 'Free',
    stars: 49000,
    downloads: 890000,
    rating: 4.5,
    reviews_count: 4560,
    homepage: 'https://bulma.io',
    repository: 'https://github.com/jgthms/bulma',
    documentation: 'https://bulma.io/documentation/',
    dependencies: [],
    tags: ['css', 'flexbox', 'responsive'],
    codeExample: `<button class="button is-primary">Primary</button>`
  },
  {
    name: 'Foundation',
    description: 'The most advanced responsive front-end framework',
    category: 'CSS Framework',
    version: '6.7.5',
    platforms: ['windows', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 29000,
    downloads: 520000,
    rating: 4.3,
    reviews_count: 3890,
    homepage: 'https://get.foundation',
    repository: 'https://github.com/foundation/foundation-sites',
    documentation: 'https://get.foundation/sites/docs/',
    dependencies: [],
    tags: ['css', 'responsive', 'sass'],
    codeExample: `<button class="button">Default Button</button>`
  },
  {
    name: 'Semantic UI',
    description: 'User Interface is the language of the web',
    category: 'CSS Framework',
    version: '2.5.0',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 51000,
    downloads: 980000,
    rating: 4.4,
    reviews_count: 6120,
    homepage: 'https://semantic-ui.com',
    repository: 'https://github.com/Semantic-Org/Semantic-UI',
    documentation: 'https://semantic-ui.com/introduction/getting-started.html',
    dependencies: ['jquery'],
    tags: ['css', 'semantic', 'theming'],
    codeExample: `<button class="ui primary button">Save</button>`
  },
  {
    name: 'Ant Design',
    description: 'An enterprise-class UI design language and React UI library',
    category: 'CSS Framework',
    version: '5.10.0',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 90000,
    downloads: 2800000,
    rating: 4.7,
    reviews_count: 8760,
    homepage: 'https://ant.design',
    repository: 'https://github.com/ant-design/ant-design',
    documentation: 'https://ant.design/docs/react/introduce',
    dependencies: ['react', 'react-dom'],
    tags: ['react', 'enterprise', 'design-system'],
    codeExample: `import { Button } from 'antd';\n\nconst App = () => <Button type="primary">Button</Button>;`
  },
  {
    name: 'Chakra UI',
    description: 'Simple, Modular and Accessible UI Components for React',
    category: 'CSS Framework',
    version: '2.8.1',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 37000,
    downloads: 1700000,
    rating: 4.8,
    reviews_count: 4290,
    homepage: 'https://chakra-ui.com',
    repository: 'https://github.com/chakra-ui/chakra-ui',
    documentation: 'https://chakra-ui.com/docs/getting-started',
    dependencies: ['react', 'react-dom'],
    tags: ['react', 'accessible', 'themeable'],
    codeExample: `import { Button } from '@chakra-ui/react';\n\n<Button colorScheme="blue">Button</Button>`
  },
  {
    name: 'Sass',
    description: 'CSS with superpowers',
    category: 'CSS Framework',
    version: '1.69.0',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 15000,
    downloads: 48000000,
    rating: 4.8,
    reviews_count: 12340,
    homepage: 'https://sass-lang.com',
    repository: 'https://github.com/sass/sass',
    documentation: 'https://sass-lang.com/documentation/',
    dependencies: [],
    tags: ['css', 'preprocessor', 'scss'],
    codeExample: `$primary-color: #333;\n\nbody {\n  color: $primary-color;\n  font: 100% Helvetica, sans-serif;\n}`
  },
  {
    name: 'Less',
    description: 'It\'s CSS, with just a little more',
    category: 'CSS Framework',
    version: '4.2.0',
    platforms: ['macos', 'linux'],
    license: 'Apache-2.0',
    cost: 'Free',
    stars: 17000,
    downloads: 9800000,
    rating: 4.4,
    reviews_count: 5670,
    homepage: 'https://lesscss.org',
    repository: 'https://github.com/less/less.js',
    documentation: 'https://lesscss.org/features/',
    dependencies: [],
    tags: ['css', 'preprocessor'],
    codeExample: `@base: #f938ab;\n\n.box {\n  color: saturate(@base, 5%);\n  border-color: lighten(@base, 30%);\n}`
  },

  // BACKEND (15 libraries)
  {
    name: 'Express',
    description: 'Fast, unopinionated, minimalist web framework for Node.js',
    category: 'Backend',
    version: '4.18.2',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 63000,
    downloads: 30000000,
    rating: 4.8,
    reviews_count: 18920,
    homepage: 'https://expressjs.com',
    repository: 'https://github.com/expressjs/express',
    documentation: 'https://expressjs.com/en/api.html',
    dependencies: ['body-parser', 'cookie-parser'],
    tags: ['nodejs', 'backend', 'api', 'web-framework'],
    codeExample: `const express = require('express');\nconst app = express();\n\napp.get('/', (req, res) => {\n  res.send('Hello World!');\n});\n\napp.listen(3000);`
  },
  {
    name: 'Django',
    description: 'The web framework for perfectionists with deadlines',
    category: 'Backend',
    version: '4.2.6',
    platforms: ['windows', 'macos', 'linux'],
    license: 'BSD-3-Clause',
    cost: 'Free',
    stars: 76000,
    downloads: 8900000,
    rating: 4.7,
    reviews_count: 15340,
    homepage: 'https://www.djangoproject.com',
    repository: 'https://github.com/django/django',
    documentation: 'https://docs.djangoproject.com/',
    dependencies: [],
    tags: ['python', 'backend', 'mvc', 'orm'],
    codeExample: `from django.http import HttpResponse\n\ndef hello(request):\n    return HttpResponse("Hello, World!")`
  },
  {
    name: 'Flask',
    description: 'A lightweight WSGI web application framework',
    category: 'Backend',
    version: '3.0.0',
    platforms: ['windows', 'macos', 'linux'],
    license: 'BSD-3-Clause',
    cost: 'Free',
    stars: 66000,
    downloads: 12000000,
    rating: 4.6,
    reviews_count: 11230,
    homepage: 'https://flask.palletsprojects.com',
    repository: 'https://github.com/pallets/flask',
    documentation: 'https://flask.palletsprojects.com/en/3.0.x/',
    dependencies: ['werkzeug', 'jinja2'],
    tags: ['python', 'backend', 'microframework'],
    codeExample: `from flask import Flask\n\napp = Flask(__name__)\n\n@app.route('/')\ndef hello():\n    return 'Hello, World!'`
  },
  {
    name: 'FastAPI',
    description: 'Modern, fast web framework for building APIs with Python',
    category: 'Backend',
    version: '0.104.1',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 71000,
    downloads: 7800000,
    rating: 4.9,
    reviews_count: 9870,
    homepage: 'https://fastapi.tiangolo.com',
    repository: 'https://github.com/tiangolo/fastapi',
    documentation: 'https://fastapi.tiangolo.com/tutorial/',
    dependencies: ['pydantic', 'starlette'],
    tags: ['python', 'backend', 'api', 'async'],
    codeExample: `from fastapi import FastAPI\n\napp = FastAPI()\n\n@app.get("/")\nasync def root():\n    return {"message": "Hello World"}`
  },
  {
    name: 'Spring Boot',
    description: 'Create stand-alone, production-grade Spring applications',
    category: 'Backend',
    version: '3.1.5',
    platforms: ['windows', 'macos', 'linux'],
    license: 'Apache-2.0',
    cost: 'Free',
    stars: 72000,
    downloads: 5600000,
    rating: 4.7,
    reviews_count: 13240,
    homepage: 'https://spring.io/projects/spring-boot',
    repository: 'https://github.com/spring-projects/spring-boot',
    documentation: 'https://spring.io/guides',
    dependencies: [],
    tags: ['java', 'backend', 'enterprise', 'spring'],
    codeExample: `@SpringBootApplication\npublic class Application {\n    public static void main(String[] args) {\n        SpringApplication.run(Application.class, args);\n    }\n}`
  },
  {
    name: 'Ruby on Rails',
    description: 'Server-side web application framework written in Ruby',
    category: 'Backend',
    version: '7.1.1',
    platforms: ['macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 55000,
    downloads: 2100000,
    rating: 4.5,
    reviews_count: 10780,
    homepage: 'https://rubyonrails.org',
    repository: 'https://github.com/rails/rails',
    documentation: 'https://guides.rubyonrails.org',
    dependencies: [],
    tags: ['ruby', 'backend', 'mvc', 'convention-over-configuration'],
    codeExample: `class ArticlesController < ApplicationController\n  def index\n    @articles = Article.all\n  end\nend`
  },
  {
    name: 'NestJS',
    description: 'A progressive Node.js framework for building server-side applications',
    category: 'Backend',
    version: '10.2.7',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 64000,
    downloads: 2800000,
    rating: 4.8,
    reviews_count: 7650,
    homepage: 'https://nestjs.com',
    repository: 'https://github.com/nestjs/nest',
    documentation: 'https://docs.nestjs.com',
    dependencies: ['express', '@nestjs/core'],
    tags: ['typescript', 'backend', 'nodejs', 'decorators'],
    codeExample: `@Controller()\nexport class AppController {\n  @Get()\n  getHello(): string {\n    return 'Hello World!';\n  }\n}`
  },
  {
    name: 'Laravel',
    description: 'The PHP Framework for Web Artisans',
    category: 'Backend',
    version: '10.28.0',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 77000,
    downloads: 4500000,
    rating: 4.7,
    reviews_count: 12890,
    homepage: 'https://laravel.com',
    repository: 'https://github.com/laravel/laravel',
    documentation: 'https://laravel.com/docs',
    dependencies: [],
    tags: ['php', 'backend', 'mvc', 'elegant'],
    codeExample: `Route::get('/', function () {\n    return view('welcome');\n});`
  },
  {
    name: 'ASP.NET Core',
    description: 'Cross-platform, high-performance framework for building modern apps',
    category: 'Backend',
    version: '7.0',
    platforms: ['windows', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 34000,
    downloads: 8900000,
    rating: 4.6,
    reviews_count: 9230,
    homepage: 'https://dotnet.microsoft.com/apps/aspnet',
    repository: 'https://github.com/dotnet/aspnetcore',
    documentation: 'https://learn.microsoft.com/aspnet/core',
    dependencies: [],
    tags: ['csharp', 'backend', 'cross-platform', 'microsoft'],
    codeExample: `var builder = WebApplication.CreateBuilder(args);\nvar app = builder.Build();\n\napp.MapGet("/", () => "Hello World!");\n\napp.Run();`
  },
  {
    name: 'Koa',
    description: 'Expressive middleware for Node.js using ES2017 async functions',
    category: 'Backend',
    version: '2.14.2',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 35000,
    downloads: 6700000,
    rating: 4.5,
    reviews_count: 4560,
    homepage: 'https://koajs.com',
    repository: 'https://github.com/koajs/koa',
    documentation: 'https://koajs.com/#introduction',
    dependencies: [],
    tags: ['nodejs', 'backend', 'async', 'middleware'],
    codeExample: `const Koa = require('koa');\nconst app = new Koa();\n\napp.use(async ctx => {\n  ctx.body = 'Hello World';\n});\n\napp.listen(3000);`
  },
  {
    name: 'Hapi',
    description: 'The Simple, Secure Framework for building powerful APIs',
    category: 'Backend',
    version: '21.3.2',
    platforms: ['macos', 'linux'],
    license: 'BSD-3-Clause',
    cost: 'Free',
    stars: 14000,
    downloads: 1200000,
    rating: 4.3,
    reviews_count: 2340,
    homepage: 'https://hapi.dev',
    repository: 'https://github.com/hapijs/hapi',
    documentation: 'https://hapi.dev/api/',
    dependencies: [],
    tags: ['nodejs', 'backend', 'api', 'configuration'],
    codeExample: `const Hapi = require('@hapi/hapi');\n\nconst init = async () => {\n    const server = Hapi.server({ port: 3000 });\n    server.route({\n        method: 'GET',\n        path: '/',\n        handler: () => 'Hello World!'\n    });\n    await server.start();\n};\ninit();`
  },
  {
    name: 'Gin',
    description: 'HTTP web framework written in Go',
    category: 'Backend',
    version: '1.9.1',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 75000,
    downloads: 2300000,
    rating: 4.8,
    reviews_count: 6780,
    homepage: 'https://gin-gonic.com',
    repository: 'https://github.com/gin-gonic/gin',
    documentation: 'https://gin-gonic.com/docs/',
    dependencies: [],
    tags: ['go', 'backend', 'fast', 'http'],
    codeExample: `package main\n\nimport "github.com/gin-gonic/gin"\n\nfunc main() {\n    r := gin.Default()\n    r.GET("/", func(c *gin.Context) {\n        c.JSON(200, gin.H{"message": "Hello World"})\n    })\n    r.Run()\n}`
  },
  {
    name: 'Echo',
    description: 'High performance, minimalist Go web framework',
    category: 'Backend',
    version: '4.11.2',
    platforms: ['linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 28000,
    downloads: 1800000,
    rating: 4.6,
    reviews_count: 3890,
    homepage: 'https://echo.labstack.com',
    repository: 'https://github.com/labstack/echo',
    documentation: 'https://echo.labstack.com/guide/',
    dependencies: [],
    tags: ['go', 'backend', 'minimalist', 'performance'],
    codeExample: `package main\n\nimport (\n    "github.com/labstack/echo/v4"\n)\n\nfunc main() {\n    e := echo.New()\n    e.GET("/", func(c echo.Context) error {\n        return c.String(200, "Hello, World!")\n    })\n    e.Start(":8080")\n}`
  },
  {
    name: 'Rocket',
    description: 'Web framework for Rust that makes it simple to write fast web applications',
    category: 'Backend',
    version: '0.5.0',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 23000,
    downloads: 450000,
    rating: 4.7,
    reviews_count: 2150,
    homepage: 'https://rocket.rs',
    repository: 'https://github.com/SergioBenitez/Rocket',
    documentation: 'https://rocket.rs/v0.5/guide/',
    dependencies: [],
    tags: ['rust', 'backend', 'type-safe', 'fast'],
    codeExample: `#[macro_use] extern crate rocket;\n\n#[get("/")]\nfn index() -> &'static str {\n    "Hello, world!"\n}\n\n#[launch]\nfn rocket() -> _ {\n    rocket::build().mount("/", routes![index])\n}`
  },
  {
    name: 'Actix Web',
    description: 'Powerful, pragmatic, and extremely fast web framework for Rust',
    category: 'Backend',
    version: '4.4.0',
    platforms: ['windows', 'macos', 'linux'],
    license: 'Apache-2.0',
    cost: 'Free',
    stars: 20000,
    downloads: 890000,
    rating: 4.8,
    reviews_count: 2780,
    homepage: 'https://actix.rs',
    repository: 'https://github.com/actix/actix-web',
    documentation: 'https://actix.rs/docs/',
    dependencies: [],
    tags: ['rust', 'backend', 'async', 'performance'],
    codeExample: `use actix_web::{web, App, HttpServer, Responder};\n\nasync fn index() -> impl Responder {\n    "Hello, World!"\n}\n\n#[actix_web::main]\nasync fn main() {\n    HttpServer::new(|| {\n        App::new().route("/", web::get().to(index))\n    }).bind("127.0.0.1:8080").unwrap().run().await;\n}`
  },

  // MACHINE LEARNING (9)
  {
    name: 'TensorFlow',
    description: 'An end-to-end open source platform for machine learning',
    category: 'Machine Learning',
    version: '2.14.0',
    platforms: ['windows', 'macos', 'linux'],
    license: 'Apache-2.0',
    cost: 'Free',
    stars: 183000,
    downloads: 8900000,
    rating: 4.7,
    reviews_count: 22340,
    homepage: 'https://www.tensorflow.org',
    repository: 'https://github.com/tensorflow/tensorflow',
    documentation: 'https://www.tensorflow.org/api_docs',
    dependencies: ['numpy'],
    tags: ['python', 'machine-learning', 'deep-learning', 'neural-networks'],
    codeExample: `import tensorflow as tf\n\nmodel = tf.keras.Sequential([\n    tf.keras.layers.Dense(128, activation='relu'),\n    tf.keras.layers.Dense(10, activation='softmax')\n])\n\nmodel.compile(optimizer='adam', loss='sparse_categorical_crossentropy')`
  },
  {
    name: 'PyTorch',
    description: 'Tensors and Dynamic neural networks in Python',
    category: 'Machine Learning',
    version: '2.1.0',
    platforms: ['windows', 'macos', 'linux'],
    license: 'BSD-3-Clause',
    cost: 'Free',
    stars: 78000,
    downloads: 12000000,
    rating: 4.8,
    reviews_count: 18920,
    homepage: 'https://pytorch.org',
    repository: 'https://github.com/pytorch/pytorch',
    documentation: 'https://pytorch.org/docs/',
    dependencies: ['numpy'],
    tags: ['python', 'machine-learning', 'deep-learning', 'research'],
    codeExample: `import torch\nimport torch.nn as nn\n\nmodel = nn.Sequential(\n    nn.Linear(784, 128),\n    nn.ReLU(),\n    nn.Linear(128, 10)\n)`
  },
  {
    name: 'scikit-learn',
    description: 'Machine Learning in Python',
    category: 'Machine Learning',
    version: '1.3.2',
    platforms: ['windows', 'macos', 'linux'],
    license: 'BSD-3-Clause',
    cost: 'Free',
    stars: 58000,
    downloads: 23000000,
    rating: 4.7,
    reviews_count: 15670,
    homepage: 'https://scikit-learn.org',
    repository: 'https://github.com/scikit-learn/scikit-learn',
    documentation: 'https://scikit-learn.org/stable/documentation.html',
    dependencies: ['numpy', 'scipy'],
    tags: ['python', 'machine-learning', 'data-mining', 'data-analysis'],
    codeExample: `from sklearn.ensemble import RandomForestClassifier\n\nclf = RandomForestClassifier(n_estimators=100)\nclf.fit(X_train, y_train)\npredictions = clf.predict(X_test)`
  },
  {
    name: 'Keras',
    description: 'Deep Learning for humans',
    category: 'Machine Learning',
    version: '2.14.0',
    platforms: ['windows', 'linux'],
    license: 'Apache-2.0',
    cost: 'Free',
    stars: 61000,
    downloads: 6700000,
    rating: 4.6,
    reviews_count: 11230,
    homepage: 'https://keras.io',
    repository: 'https://github.com/keras-team/keras',
    documentation: 'https://keras.io/api/',
    dependencies: ['tensorflow'],
    tags: ['python', 'deep-learning', 'neural-networks', 'api'],
    codeExample: `from keras.models import Sequential\nfrom keras.layers import Dense\n\nmodel = Sequential([\n    Dense(64, activation='relu', input_shape=(784,)),\n    Dense(10, activation='softmax')\n])\nmodel.compile(optimizer='adam', loss='categorical_crossentropy')`
  },
  {
    name: 'XGBoost',
    description: 'Scalable, Portable and Distributed Gradient Boosting',
    category: 'Machine Learning',
    version: '2.0.0',
    platforms: ['windows', 'macos', 'linux'],
    license: 'Apache-2.0',
    cost: 'Free',
    stars: 25000,
    downloads: 8900000,
    rating: 4.7,
    reviews_count: 7890,
    homepage: 'https://xgboost.readthedocs.io',
    repository: 'https://github.com/dmlc/xgboost',
    documentation: 'https://xgboost.readthedocs.io/en/stable/',
    dependencies: ['numpy', 'scipy'],
    tags: ['python', 'gradient-boosting', 'machine-learning', 'kaggle'],
    codeExample: `import xgboost as xgb\n\nmodel = xgb.XGBClassifier(n_estimators=100, max_depth=3)\nmodel.fit(X_train, y_train)\npredictions = model.predict(X_test)`
  },
  {
    name: 'LightGBM',
    description: 'A fast, distributed, high performance gradient boosting framework',
    category: 'Machine Learning',
    version: '4.1.0',
    platforms: ['macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 16000,
    downloads: 5600000,
    rating: 4.6,
    reviews_count: 4230,
    homepage: 'https://lightgbm.readthedocs.io',
    repository: 'https://github.com/microsoft/LightGBM',
    documentation: 'https://lightgbm.readthedocs.io/en/latest/',
    dependencies: ['numpy', 'scipy'],
    tags: ['python', 'gradient-boosting', 'machine-learning', 'microsoft'],
    codeExample: `import lightgbm as lgb\n\ntrain_data = lgb.Dataset(X_train, label=y_train)\nparams = {'objective': 'binary', 'metric': 'auc'}\nmodel = lgb.train(params, train_data, num_boost_round=100)`
  },
  {
    name: 'Hugging Face Transformers',
    description: 'State-of-the-art Natural Language Processing for PyTorch and TensorFlow',
    category: 'Machine Learning',
    version: '4.34.1',
    platforms: ['windows', 'macos', 'linux'],
    license: 'Apache-2.0',
    cost: 'Free',
    stars: 125000,
    downloads: 12500000,
    rating: 4.9,
    reviews_count: 18750,
    homepage: 'https://huggingface.co/transformers',
    repository: 'https://github.com/huggingface/transformers',
    documentation: 'https://huggingface.co/docs/transformers',
    dependencies: ['torch', 'numpy'],
    tags: ['python', 'nlp', 'transformers', 'bert', 'gpt'],
    codeExample: `from transformers import pipeline\n\nclassifier = pipeline('sentiment-analysis')\nresult = classifier('I love this library!')\nprint(result)`
  },
  {
    name: 'spaCy',
    description: 'Industrial-strength Natural Language Processing',
    category: 'Machine Learning',
    version: '3.7.2',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 29000,
    downloads: 7800000,
    rating: 4.7,
    reviews_count: 9340,
    homepage: 'https://spacy.io',
    repository: 'https://github.com/explosion/spaCy',
    documentation: 'https://spacy.io/api',
    dependencies: [],
    tags: ['python', 'nlp', 'linguistics', 'text-processing'],
    codeExample: `import spacy\n\nnlp = spacy.load("en_core_web_sm")\ndoc = nlp("Apple is looking at buying U.K. startup")\nfor token in doc:\n    print(token.text, token.pos_, token.dep_)`
  },
  {
    name: 'OpenCV',
    description: 'Open Source Computer Vision Library',
    category: 'Machine Learning',
    version: '4.8.1',
    platforms: ['windows', 'macos', 'linux'],
    license: 'Apache-2.0',
    cost: 'Free',
    stars: 76000,
    downloads: 9200000,
    rating: 4.6,
    reviews_count: 16780,
    homepage: 'https://opencv.org',
    repository: 'https://github.com/opencv/opencv',
    documentation: 'https://docs.opencv.org',
    dependencies: ['numpy'],
    tags: ['python', 'computer-vision', 'image-processing', 'video'],
    codeExample: `import cv2\n\nimage = cv2.imread('photo.jpg')\ngray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)\ncv2.imshow('Gray Image', gray)\ncv2.waitKey(0)`
  },

  // DATA SCIENCE (6)
  {
    name: 'Pandas',
    description: 'Powerful data structures for data analysis',
    category: 'Data Science',
    version: '2.1.3',
    platforms: ['windows', 'macos', 'linux'],
    license: 'BSD-3-Clause',
    cost: 'Free',
    stars: 42000,
    downloads: 45000000,
    rating: 4.8,
    reviews_count: 19870,
    homepage: 'https://pandas.pydata.org',
    repository: 'https://github.com/pandas-dev/pandas',
    documentation: 'https://pandas.pydata.org/docs/',
    dependencies: ['numpy'],
    tags: ['python', 'data-analysis', 'dataframe', 'statistics'],
    codeExample: `import pandas as pd\n\ndf = pd.DataFrame({\n    'Name': ['Alice', 'Bob'],\n    'Age': [25, 30]\n})\nprint(df.describe())`
  },
  {
    name: 'NumPy',
    description: 'The fundamental package for scientific computing with Python',
    category: 'Data Science',
    version: '1.26.1',
    platforms: ['windows', 'macos', 'linux'],
    license: 'BSD-3-Clause',
    cost: 'Free',
    stars: 26000,
    downloads: 98000000,
    rating: 4.9,
    reviews_count: 24560,
    homepage: 'https://numpy.org',
    repository: 'https://github.com/numpy/numpy',
    documentation: 'https://numpy.org/doc/',
    dependencies: [],
    tags: ['python', 'scientific-computing', 'arrays', 'mathematics'],
    codeExample: `import numpy as np\n\narr = np.array([1, 2, 3, 4, 5])\nprint(arr.mean())\nprint(arr.std())`
  },
  {
    name: 'Matplotlib',
    description: 'Python plotting library',
    category: 'Data Science',
    version: '3.8.1',
    platforms: ['windows', 'linux'],
    license: 'PSF',
    cost: 'Free',
    stars: 19000,
    downloads: 32000000,
    rating: 4.5,
    reviews_count: 11230,
    homepage: 'https://matplotlib.org',
    repository: 'https://github.com/matplotlib/matplotlib',
    documentation: 'https://matplotlib.org/stable/index.html',
    dependencies: ['numpy'],
    tags: ['python', 'visualization', 'plotting', 'charts'],
    codeExample: `import matplotlib.pyplot as plt\n\nplt.plot([1, 2, 3, 4], [1, 4, 9, 16])\nplt.xlabel('X axis')\nplt.ylabel('Y axis')\nplt.show()`
  },
  {
    name: 'Seaborn',
    description: 'Statistical data visualization',
    category: 'Data Science',
    version: '0.13.0',
    platforms: ['macos', 'linux'],
    license: 'BSD-3-Clause',
    cost: 'Free',
    stars: 12000,
    downloads: 18000000,
    rating: 4.6,
    reviews_count: 6780,
    homepage: 'https://seaborn.pydata.org',
    repository: 'https://github.com/mwaskom/seaborn',
    documentation: 'https://seaborn.pydata.org/tutorial.html',
    dependencies: ['matplotlib', 'pandas'],
    tags: ['python', 'visualization', 'statistical', 'plots'],
    codeExample: `import seaborn as sns\nimport matplotlib.pyplot as plt\n\ntips = sns.load_dataset("tips")\nsns.scatterplot(data=tips, x="total_bill", y="tip")\nplt.show()`
  },
  {
    name: 'SciPy',
    description: 'Scientific computing tools for Python',
    category: 'Data Science',
    version: '1.11.3',
    platforms: ['windows', 'macos', 'linux'],
    license: 'BSD-3-Clause',
    cost: 'Free',
    stars: 13000,
    downloads: 42000000,
    rating: 4.7,
    reviews_count: 9340,
    homepage: 'https://scipy.org',
    repository: 'https://github.com/scipy/scipy',
    documentation: 'https://docs.scipy.org/doc/scipy/',
    dependencies: ['numpy'],
    tags: ['python', 'scientific-computing', 'optimization', 'integration'],
    codeExample: `from scipy import optimize\n\ndef f(x):\n    return x**2 + 2*x + 1\n\nresult = optimize.minimize(f, x0=0)\nprint(result.x)`
  },
  {
    name: 'Statsmodels',
    description: 'Statistical modeling and econometrics',
    category: 'Data Science',
    version: '0.14.0',
    platforms: ['windows', 'macos', 'linux'],
    license: 'BSD-3-Clause',
    cost: 'Free',
    stars: 9500,
    downloads: 12000000,
    rating: 4.4,
    reviews_count: 4560,
    homepage: 'https://www.statsmodels.org',
    repository: 'https://github.com/statsmodels/statsmodels',
    documentation: 'https://www.statsmodels.org/stable/index.html',
    dependencies: ['numpy', 'scipy', 'pandas'],
    tags: ['python', 'statistics', 'econometrics', 'regression'],
    codeExample: `import statsmodels.api as sm\n\nX = sm.add_constant(X_data)\nmodel = sm.OLS(y, X)\nresults = model.fit()\nprint(results.summary())`
  },

  // DATABASE (10)
  {
    name: 'Mongoose',
    description: 'MongoDB object modeling for Node.js',
    category: 'Database',
    version: '8.0.0',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 26000,
    downloads: 8900000,
    rating: 4.6,
    reviews_count: 12340,
    homepage: 'https://mongoosejs.com',
    repository: 'https://github.com/Automattic/mongoose',
    documentation: 'https://mongoosejs.com/docs/',
    dependencies: ['mongodb'],
    tags: ['nodejs', 'mongodb', 'orm', 'database'],
    codeExample: `const mongoose = require('mongoose');\n\nconst userSchema = new mongoose.Schema({\n  name: String,\n  email: String\n});\n\nconst User = mongoose.model('User', userSchema);`
  },
  {
    name: 'Sequelize',
    description: 'Feature-rich ORM for Node.js',
    category: 'Database',
    version: '6.33.0',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 29000,
    downloads: 5600000,
    rating: 4.5,
    reviews_count: 9870,
    homepage: 'https://sequelize.org',
    repository: 'https://github.com/sequelize/sequelize',
    documentation: 'https://sequelize.org/docs/v6/',
    dependencies: [],
    tags: ['nodejs', 'orm', 'sql', 'postgresql', 'mysql'],
    codeExample: `const { Sequelize, DataTypes } = require('sequelize');\nconst sequelize = new Sequelize('database', 'username', 'password');\n\nconst User = sequelize.define('User', {\n  username: DataTypes.STRING,\n  email: DataTypes.STRING\n});`
  },
  {
    name: 'TypeORM',
    description: 'ORM for TypeScript and JavaScript',
    category: 'Database',
    version: '0.3.17',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 33000,
    downloads: 3200000,
    rating: 4.6,
    reviews_count: 7650,
    homepage: 'https://typeorm.io',
    repository: 'https://github.com/typeorm/typeorm',
    documentation: 'https://typeorm.io/#/',
    dependencies: ['reflect-metadata'],
    tags: ['typescript', 'orm', 'database', 'decorators'],
    codeExample: `@Entity()\nexport class User {\n  @PrimaryGeneratedColumn()\n  id: number;\n\n  @Column()\n  name: string;\n\n  @Column()\n  email: string;\n}`
  },
  {
    name: 'Prisma',
    description: 'Next-generation Node.js and TypeScript ORM',
    category: 'Database',
    version: '5.5.2',
    platforms: ['windows', 'macos', 'linux'],
    license: 'Apache-2.0',
    cost: 'Free',
    stars: 37000,
    downloads: 4500000,
    rating: 4.8,
    reviews_count: 8920,
    homepage: 'https://www.prisma.io',
    repository: 'https://github.com/prisma/prisma',
    documentation: 'https://www.prisma.io/docs',
    dependencies: [],
    tags: ['typescript', 'orm', 'database', 'type-safe'],
    codeExample: `model User {\n  id    Int     @id @default(autoincrement())\n  email String  @unique\n  name  String?\n  posts Post[]\n}`
  },
  {
    name: 'SQLAlchemy',
    description: 'The Python SQL Toolkit and ORM',
    category: 'Database',
    version: '2.0.23',
    platforms: ['windows', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 8500,
    downloads: 34000000,
    rating: 4.7,
    reviews_count: 11230,
    homepage: 'https://www.sqlalchemy.org',
    repository: 'https://github.com/sqlalchemy/sqlalchemy',
    documentation: 'https://docs.sqlalchemy.org',
    dependencies: [],
    tags: ['python', 'orm', 'sql', 'database'],
    codeExample: `from sqlalchemy import Column, Integer, String\nfrom sqlalchemy.ext.declarative import declarative_base\n\nBase = declarative_base()\n\nclass User(Base):\n    __tablename__ = 'users'\n    id = Column(Integer, primary_key=True)\n    name = Column(String)\n    email = Column(String)`
  },
  {
    name: 'Redis',
    description: 'In-memory data structure store',
    category: 'Database',
    version: '7.2.0',
    platforms: ['macos', 'linux'],
    license: 'BSD-3-Clause',
    cost: 'Free',
    stars: 64000,
    downloads: 12000000,
    rating: 4.8,
    reviews_count: 18750,
    homepage: 'https://redis.io',
    repository: 'https://github.com/redis/redis',
    documentation: 'https://redis.io/documentation',
    dependencies: [],
    tags: ['cache', 'nosql', 'in-memory', 'key-value'],
    codeExample: `import redis\n\nr = redis.Redis(host='localhost', port=6379)\nr.set('key', 'value')\nvalue = r.get('key')`
  },
  {
    name: 'MongoDB Driver',
    description: 'Official MongoDB driver for Node.js',
    category: 'Database',
    version: '6.2.0',
    platforms: ['windows', 'macos', 'linux'],
    license: 'Apache-2.0',
    cost: 'Free',
    stars: 9900,
    downloads: 18000000,
    rating: 4.5,
    reviews_count: 13450,
    homepage: 'https://www.mongodb.com/docs/drivers/node/',
    repository: 'https://github.com/mongodb/node-mongodb-native',
    documentation: 'https://mongodb.github.io/node-mongodb-native/',
    dependencies: [],
    tags: ['nodejs', 'mongodb', 'nosql', 'database'],
    codeExample: `const { MongoClient } = require('mongodb');\n\nconst client = new MongoClient(url);\nawait client.connect();\nconst db = client.db('mydb');\nconst collection = db.collection('users');`
  },
  {
    name: 'PostgreSQL Driver (pg)',
    description: 'Non-blocking PostgreSQL client for Node.js',
    category: 'Database',
    version: '8.11.3',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 12000,
    downloads: 23000000,
    rating: 4.6,
    reviews_count: 9870,
    homepage: 'https://node-postgres.com',
    repository: 'https://github.com/brianc/node-postgres',
    documentation: 'https://node-postgres.com/features/connecting',
    dependencies: [],
    tags: ['nodejs', 'postgresql', 'sql', 'database'],
    codeExample: `const { Client } = require('pg');\n\nconst client = new Client();\nawait client.connect();\nconst res = await client.query('SELECT NOW()');\nawait client.end();`
  },
  {
    name: 'Knex.js',
    description: 'SQL query builder for PostgreSQL, MySQL and SQLite3',
    category: 'Database',
    version: '3.0.1',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 19000,
    downloads: 7800000,
    rating: 4.5,
    reviews_count: 6780,
    homepage: 'https://knexjs.org',
    repository: 'https://github.com/knex/knex',
    documentation: 'https://knexjs.org/guide/',
    dependencies: [],
    tags: ['nodejs', 'sql', 'query-builder', 'migrations'],
    codeExample: `const knex = require('knex')({\n  client: 'postgresql',\n  connection: 'postgres://user:pass@localhost:5432/db'\n});\n\nconst users = await knex('users').where('age', '>', 18).select('name', 'email');`
  },
  {
    name: 'Drizzle ORM',
    description: 'TypeScript ORM that is production-ready',
    category: 'Database',
    version: '0.29.0',
    platforms: ['windows', 'macos', 'linux'],
    license: 'Apache-2.0',
    cost: 'Free',
    stars: 18000,
    downloads: 580000,
    rating: 4.8,
    reviews_count: 2340,
    homepage: 'https://orm.drizzle.team',
    repository: 'https://github.com/drizzle-team/drizzle-orm',
    documentation: 'https://orm.drizzle.team/docs/overview',
    dependencies: [],
    tags: ['typescript', 'orm', 'type-safe', 'sql'],
    codeExample: `import { drizzle } from 'drizzle-orm/node-postgres';\nimport { pgTable, serial, text } from 'drizzle-orm/pg-core';\n\nconst users = pgTable('users', {\n  id: serial('id').primaryKey(),\n  name: text('name')\n});`
  },

  // TESTING (10)
  {
    name: 'Jest',
    description: 'Delightful JavaScript Testing',
    category: 'Testing',
    version: '29.7.0',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 43000,
    downloads: 38000000,
    rating: 4.7,
    reviews_count: 15670,
    homepage: 'https://jestjs.io',
    repository: 'https://github.com/jestjs/jest',
    documentation: 'https://jestjs.io/docs/getting-started',
    dependencies: [],
    tags: ['javascript', 'testing', 'unit-test', 'snapshot'],
    codeExample: `test('adds 1 + 2 to equal 3', () => {\n  expect(1 + 2).toBe(3);\n});\n\ntest('object assignment', () => {\n  const data = {one: 1};\n  data['two'] = 2;\n  expect(data).toEqual({one: 1, two: 2});\n});`
  },
  {
    name: 'Mocha',
    description: 'Simple, flexible, fun JavaScript test framework',
    category: 'Testing',
    version: '10.2.0',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 22000,
    downloads: 24000000,
    rating: 4.5,
    reviews_count: 12340,
    homepage: 'https://mochajs.org',
    repository: 'https://github.com/mochajs/mocha',
    documentation: 'https://mochajs.org/#getting-started',
    dependencies: [],
    tags: ['javascript', 'testing', 'bdd', 'tdd'],
    codeExample: `describe('Array', function() {\n  describe('#indexOf()', function() {\n    it('should return -1 when value not present', function() {\n      assert.equal([1, 2, 3].indexOf(4), -1);\n    });\n  });\n});`
  },
  {
    name: 'Pytest',
    description: 'The pytest framework makes it easy to write tests',
    category: 'Testing',
    version: '7.4.3',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 11000,
    downloads: 56000000,
    rating: 4.8,
    reviews_count: 18920,
    homepage: 'https://docs.pytest.org',
    repository: 'https://github.com/pytest-dev/pytest',
    documentation: 'https://docs.pytest.org/en/stable/',
    dependencies: [],
    tags: ['python', 'testing', 'unit-test', 'fixtures'],
    codeExample: `def test_addition():\n    assert 1 + 1 == 2\n\ndef test_string_length():\n    assert len("hello") == 5\n\ndef test_list_contains():\n    assert 3 in [1, 2, 3, 4]`
  },
  {
    name: 'Cypress',
    description: 'Fast, easy and reliable testing for anything that runs in a browser',
    category: 'Testing',
    version: '13.4.0',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 46000,
    downloads: 6700000,
    rating: 4.7,
    reviews_count: 11230,
    homepage: 'https://www.cypress.io',
    repository: 'https://github.com/cypress-io/cypress',
    documentation: 'https://docs.cypress.io',
    dependencies: [],
    tags: ['javascript', 'e2e-testing', 'testing', 'browser'],
    codeExample: `describe('My First Test', () => {\n  it('Visits the app', () => {\n    cy.visit('https://example.com')\n    cy.contains('type').click()\n    cy.url().should('include', '/commands/actions')\n  })\n})`
  },
  {
    name: 'Playwright',
    description: 'Fast and reliable end-to-end testing for modern web apps',
    category: 'Testing',
    version: '1.39.0',
    platforms: ['windows', 'macos', 'linux'],
    license: 'Apache-2.0',
    cost: 'Free',
    stars: 62000,
    downloads: 8900000,
    rating: 4.9,
    reviews_count: 9870,
    homepage: 'https://playwright.dev',
    repository: 'https://github.com/microsoft/playwright',
    documentation: 'https://playwright.dev/docs/intro',
    dependencies: [],
    tags: ['javascript', 'e2e-testing', 'automation', 'cross-browser'],
    codeExample: `const { test, expect } = require('@playwright/test');\n\ntest('basic test', async ({ page }) => {\n  await page.goto('https://playwright.dev/');\n  const title = await page.textContent('.hero__title');\n  expect(title).toBe('Playwright');\n});`
  },
  {
    name: 'Selenium',
    description: 'Browser automation framework and ecosystem',
    category: 'Testing',
    version: '4.15.0',
    platforms: ['windows', 'linux'],
    license: 'Apache-2.0',
    cost: 'Free',
    stars: 29000,
    downloads: 7800000,
    rating: 4.4,
    reviews_count: 16780,
    homepage: 'https://www.selenium.dev',
    repository: 'https://github.com/SeleniumHQ/selenium',
    documentation: 'https://www.selenium.dev/documentation/',
    dependencies: [],
    tags: ['automation', 'browser-testing', 'e2e', 'webdriver'],
    codeExample: `from selenium import webdriver\nfrom selenium.webdriver.common.by import By\n\ndriver = webdriver.Chrome()\ndriver.get("https://www.example.com")\nelement = driver.find_element(By.ID, "submit")\nelement.click()`
  },
  {
    name: 'Testing Library',
    description: 'Simple and complete testing utilities',
    category: 'Testing',
    version: '14.1.2',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 18000,
    downloads: 32000000,
    rating: 4.8,
    reviews_count: 8920,
    homepage: 'https://testing-library.com',
    repository: 'https://github.com/testing-library/react-testing-library',
    documentation: 'https://testing-library.com/docs/react-testing-library/intro/',
    dependencies: ['react', 'react-dom'],
    tags: ['react', 'testing', 'dom', 'accessibility'],
    codeExample: `import { render, screen } from '@testing-library/react';\nimport userEvent from '@testing-library/user-event';\n\ntest('loads and displays greeting', async () => {\n  render(<Greeting />)\n  expect(screen.getByRole('heading')).toHaveTextContent('hello')\n})`
  },
  {
    name: 'Vitest',
    description: 'Next generation testing framework powered by Vite',
    category: 'Testing',
    version: '0.34.6',
    platforms: ['macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 12000,
    downloads: 4500000,
    rating: 4.7,
    reviews_count: 3420,
    homepage: 'https://vitest.dev',
    repository: 'https://github.com/vitest-dev/vitest',
    documentation: 'https://vitest.dev/guide/',
    dependencies: [],
    tags: ['javascript', 'testing', 'vite', 'fast'],
    codeExample: `import { describe, it, expect } from 'vitest'\n\ndescribe('sum', () => {\n  it('adds 1 + 2 to equal 3', () => {\n    expect(1 + 2).toBe(3)\n  })\n})`
  },
  {
    name: 'ESLint',
    description: 'Find and fix problems in your JavaScript code',
    category: 'Testing',
    version: '8.52.0',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 24000,
    downloads: 78000000,
    rating: 4.6,
    reviews_count: 22150,
    homepage: 'https://eslint.org',
    repository: 'https://github.com/eslint/eslint',
    documentation: 'https://eslint.org/docs/latest/',
    dependencies: [],
    tags: ['javascript', 'linter', 'code-quality', 'static-analysis'],
    codeExample: `module.exports = {\n  extends: 'eslint:recommended',\n  rules: {\n    'no-unused-vars': 'error',\n    'no-console': 'warn'\n  }\n};`
  },
  {
    name: 'Prettier',
    description: 'Opinionated code formatter',
    category: 'Testing',
    version: '3.0.3',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 48000,
    downloads: 28000000,
    rating: 4.7,
    reviews_count: 19340,
    homepage: 'https://prettier.io',
    repository: 'https://github.com/prettier/prettier',
    documentation: 'https://prettier.io/docs/en/index.html',
    dependencies: [],
    tags: ['javascript', 'formatting', 'code-quality', 'style'],
    codeExample: `// .prettierrc\n{\n  "semi": true,\n  "trailingComma": "all",\n  "singleQuote": true,\n  "printWidth": 80,\n  "tabWidth": 2\n}`
  },

  // UTILITY (15)
  {
    name: 'Lodash',
    description: 'A modern JavaScript utility library',
    category: 'Utility',
    version: '4.17.21',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 59000,
    downloads: 150000000,
    rating: 4.7,
    reviews_count: 28760,
    homepage: 'https://lodash.com',
    repository: 'https://github.com/lodash/lodash',
    documentation: 'https://lodash.com/docs/',
    dependencies: [],
    tags: ['javascript', 'utility', 'functions', 'array'],
    codeExample: `const _ = require('lodash');\n\nconst users = [{ 'user': 'fred', 'age': 48 }, { 'user': 'barney', 'age': 36 }];\nconsole.log(_.map(users, 'user'));\nconsole.log(_.sortBy(users, ['age']));`
  },
  {
    name: 'Moment.js',
    description: 'Parse, validate, manipulate, and display dates',
    category: 'Utility',
    version: '2.29.4',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 47000,
    downloads: 18000000,
    rating: 4.5,
    reviews_count: 24560,
    homepage: 'https://momentjs.com',
    repository: 'https://github.com/moment/moment',
    documentation: 'https://momentjs.com/docs/',
    dependencies: [],
    tags: ['javascript', 'date', 'time', 'formatting'],
    codeExample: `const moment = require('moment');\n\nconst now = moment();\nconsole.log(now.format('MMMM Do YYYY, h:mm:ss a'));\nconsole.log(moment([2020, 0, 1]).fromNow());`
  },
  {
    name: 'Day.js',
    description: '2kB immutable date-time library alternative to Moment.js',
    category: 'Utility',
    version: '1.11.10',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 46000,
    downloads: 23000000,
    rating: 4.8,
    reviews_count: 9870,
    homepage: 'https://day.js.org',
    repository: 'https://github.com/iamkun/dayjs',
    documentation: 'https://day.js.org/docs/en/installation/installation',
    dependencies: [],
    tags: ['javascript', 'date', 'time', 'lightweight'],
    codeExample: `const dayjs = require('dayjs');\n\nconst now = dayjs();\nconsole.log(now.format('YYYY-MM-DD'));\nconsole.log(dayjs('2020-01-01').fromNow());`
  },
  {
    name: 'Axios',
    description: 'Promise based HTTP client',
    category: 'Utility',
    version: '1.6.0',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 105000,
    downloads: 98000000,
    rating: 4.8,
    reviews_count: 34560,
    homepage: 'https://axios-http.com',
    repository: 'https://github.com/axios/axios',
    documentation: 'https://axios-http.com/docs/intro',
    dependencies: [],
    tags: ['javascript', 'http', 'ajax', 'promise'],
    codeExample: `const axios = require('axios');\n\naxios.get('https://api.example.com/users')\n  .then(response => console.log(response.data))\n  .catch(error => console.error(error));`
  },
  {
    name: 'Ramda',
    description: 'A practical functional library for JavaScript',
    category: 'Utility',
    version: '0.29.1',
    platforms: ['windows', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 23000,
    downloads: 6700000,
    rating: 4.6,
    reviews_count: 5670,
    homepage: 'https://ramdajs.com',
    repository: 'https://github.com/ramda/ramda',
    documentation: 'https://ramdajs.com/docs/',
    dependencies: [],
    tags: ['javascript', 'functional', 'utility', 'immutable'],
    codeExample: `const R = require('ramda');\n\nconst double = x => x * 2;\nconst isEven = x => x % 2 === 0;\nconst doubleEvens = R.compose(R.map(double), R.filter(isEven));\nconsole.log(doubleEvens([1, 2, 3, 4]));`
  },
  {
    name: 'UUID',
    description: 'Generate RFC-compliant UUIDs',
    category: 'Utility',
    version: '9.0.1',
    platforms: ['macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 14000,
    downloads: 180000000,
    rating: 4.7,
    reviews_count: 18920,
    homepage: 'https://github.com/uuidjs/uuid',
    repository: 'https://github.com/uuidjs/uuid',
    documentation: 'https://github.com/uuidjs/uuid#readme',
    dependencies: [],
    tags: ['javascript', 'unique-id', 'javascript', 'uuid'],
    codeExample: `const { v4: uuidv4 } = require('uuid');\n\nconst id = uuidv4();\nconsole.log(id); // ⇨ '1b9d6bcd-bbfd-4b2d-9b5d-ab8dfbbd4bed'`
  },
  {
    name: 'Joi',
    description: 'The most powerful data validation library for JS',
    category: 'Utility',
    version: '17.11.0',
    platforms: ['windows', 'macos', 'linux'],
    license: 'BSD-3-Clause',
    cost: 'Free',
    stars: 20000,
    downloads: 12000000,
    rating: 4.7,
    reviews_count: 8920,
    homepage: 'https://joi.dev',
    repository: 'https://github.com/hapijs/joi',
    documentation: 'https://joi.dev/api/',
    dependencies: [],
    tags: ['javascript', 'validation', 'schema', 'data'],
    codeExample: `const Joi = require('joi');\n\nconst schema = Joi.object({\n  username: Joi.string().alphanum().min(3).max(30).required(),\n  email: Joi.string().email().required()\n});\n\nconst result = schema.validate({ username: 'abc', email: 'test@test.com' });`
  },
  {
    name: 'Yup',
    description: 'Dead simple Object schema validation',
    category: 'Utility',
    version: '1.3.3',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 22000,
    downloads: 18000000,
    rating: 4.6,
    reviews_count: 9340,
    homepage: 'https://github.com/jquense/yup',
    repository: 'https://github.com/jquense/yup',
    documentation: 'https://github.com/jquense/yup#readme',
    dependencies: [],
    tags: ['javascript', 'validation', 'schema', 'forms'],
    codeExample: `const yup = require('yup');\n\nconst schema = yup.object({\n  name: yup.string().required(),\n  age: yup.number().required().positive().integer(),\n  email: yup.string().email()\n});\n\nschema.validate({ name: 'John', age: 30 });`
  },
  {
    name: 'Zod',
    description: 'TypeScript-first schema validation with static type inference',
    category: 'Utility',
    version: '3.22.4',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 30000,
    downloads: 15000000,
    rating: 4.9,
    reviews_count: 7650,
    homepage: 'https://zod.dev',
    repository: 'https://github.com/colinhacks/zod',
    documentation: 'https://zod.dev',
    dependencies: [],
    tags: ['typescript', 'validation', 'schema', 'type-safe'],
    codeExample: `import { z } from 'zod';\n\nconst User = z.object({\n  username: z.string(),\n  age: z.number().min(18),\n  email: z.string().email()\n});\n\ntype User = z.infer<typeof User>;`
  },
  {
    name: 'dotenv',
    description: 'Loads environment variables from .env file',
    category: 'Utility',
    version: '16.3.1',
    platforms: ['windows', 'macos', 'linux'],
    license: 'BSD-2-Clause',
    cost: 'Free',
    stars: 18000,
    downloads: 400000000,
    rating: 4.8,
    reviews_count: 34560,
    homepage: 'https://github.com/motdotla/dotenv',
    repository: 'https://github.com/motdotla/dotenv',
    documentation: 'https://github.com/motdotla/dotenv#readme',
    dependencies: [],
    tags: ['javascript', 'environment', 'config', 'nodejs'],
    codeExample: `require('dotenv').config();\n\nconsole.log(process.env.DB_HOST);\nconsole.log(process.env.API_KEY);`
  },
  {
    name: 'Winston',
    description: 'A logger for just about everything',
    category: 'Utility',
    version: '3.11.0',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 22000,
    downloads: 23000000,
    rating: 4.6,
    reviews_count: 11230,
    homepage: 'https://github.com/winstonjs/winston',
    repository: 'https://github.com/winstonjs/winston',
    documentation: 'https://github.com/winstonjs/winston#readme',
    dependencies: [],
    tags: ['javascript', 'logging', 'nodejs', 'debugging'],
    codeExample: `const winston = require('winston');\n\nconst logger = winston.createLogger({\n  level: 'info',\n  format: winston.format.json(),\n  transports: [\n    new winston.transports.File({ filename: 'error.log', level: 'error' }),\n    new winston.transports.File({ filename: 'combined.log' })\n  ]\n});\n\nlogger.info('Hello world');`
  },
  {
    name: 'Chalk',
    description: 'Terminal string styling done right',
    category: 'Utility',
    version: '5.3.0',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 21000,
    downloads: 98000000,
    rating: 4.7,
    reviews_count: 15670,
    homepage: 'https://github.com/chalk/chalk',
    repository: 'https://github.com/chalk/chalk',
    documentation: 'https://github.com/chalk/chalk#readme',
    dependencies: [],
    tags: ['javascript', 'terminal', 'color', 'cli'],
    codeExample: `import chalk from 'chalk';\n\nconsole.log(chalk.blue('Hello world!'));\nconsole.log(chalk.red.bold('Error message'));\nconsole.log(chalk.green.inverse('Success!'));`
  },
  {
    name: 'Commander.js',
    description: 'The complete solution for node.js command-line interfaces',
    category: 'Utility',
    version: '11.1.0',
    platforms: ['windows', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 26000,
    downloads: 120000000,
    rating: 4.6,
    reviews_count: 18920,
    homepage: 'https://github.com/tj/commander.js',
    repository: 'https://github.com/tj/commander.js',
    documentation: 'https://github.com/tj/commander.js#readme',
    dependencies: [],
    tags: ['javascript', 'cli', 'command-line', 'nodejs'],
    codeExample: `const { program } = require('commander');\n\nprogram\n  .version('1.0.0')\n  .option('-d, --debug', 'output extra debugging')\n  .option('-s, --small', 'small pizza size')\n  .parse(process.argv);`
  },
  {
    name: 'Inquirer.js',
    description: 'A collection of common interactive command line user interfaces',
    category: 'Utility',
    version: '9.2.12',
    platforms: ['macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 19000,
    downloads: 32000000,
    rating: 4.7,
    reviews_count: 9340,
    homepage: 'https://github.com/SBoudrias/Inquirer.js',
    repository: 'https://github.com/SBoudrias/Inquirer.js',
    documentation: 'https://github.com/SBoudrias/Inquirer.js#readme',
    dependencies: [],
    tags: ['javascript', 'cli', 'prompt', 'interactive'],
    codeExample: `const inquirer = require('inquirer');\n\ninquirer.prompt([\n  {\n    type: 'input',\n    name: 'name',\n    message: 'What is your name?'\n  }\n]).then(answers => {\n  console.log(\`Hello \${answers.name}!\`);\n});`
  },
  {
    name: 'Bcrypt',
    description: 'A library to help you hash passwords',
    category: 'Utility',
    version: '5.1.1',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 7000,
    downloads: 60000000,
    rating: 4.8,
    reviews_count: 22150,
    homepage: 'https://github.com/kelektiv/node.bcrypt.js',
    repository: 'https://github.com/kelektiv/node.bcrypt.js',
    documentation: 'https://github.com/kelektiv/node.bcrypt.js#readme',
    dependencies: [],
    tags: ['javascript', 'password', 'hashing', 'security'],
    codeExample: `const bcrypt = require('bcrypt');\n\nconst hash = await bcrypt.hash('myPassword', 10);\nconst match = await bcrypt.compare('myPassword', hash);\nconsole.log(match); // true`
  },

  // BUILD TOOLS (10)
  {
    name: 'Webpack',
    description: 'A bundler for javascript and friends',
    category: 'Build Tool',
    version: '5.89.0',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 64000,
    downloads: 45000000,
    rating: 4.5,
    reviews_count: 24560,
    homepage: 'https://webpack.js.org',
    repository: 'https://github.com/webpack/webpack',
    documentation: 'https://webpack.js.org/concepts/',
    dependencies: [],
    tags: ['javascript', 'bundler', 'build-tool', 'module'],
    codeExample: `module.exports = {\n  entry: './src/index.js',\n  output: {\n    filename: 'bundle.js',\n    path: __dirname + '/dist'\n  },\n  module: {\n    rules: [\n      { test: /\\.css$/, use: ['style-loader', 'css-loader'] }\n    ]\n  }\n};`
  },
  {
    name: 'Vite',
    description: 'Next Generation Frontend Tooling',
    category: 'Build Tool',
    version: '4.5.0',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 65000,
    downloads: 12500000,
    rating: 4.9,
    reviews_count: 15670,
    homepage: 'https://vitejs.dev',
    repository: 'https://github.com/vitejs/vite',
    documentation: 'https://vitejs.dev/guide/',
    dependencies: [],
    tags: ['javascript', 'bundler', 'build-tool', 'fast'],
    codeExample: `// vite.config.js\nimport { defineConfig } from 'vite'\nimport react from '@vitejs/plugin-react'\n\nexport default defineConfig({\n  plugins: [react()],\n  server: { port: 3000 }\n})`
  },
  {
    name: 'Rollup',
    description: 'Next-generation ES module bundler',
    category: 'Build Tool',
    version: '4.3.0',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 25000,
    downloads: 23000000,
    rating: 4.6,
    reviews_count: 9870,
    homepage: 'https://rollupjs.org',
    repository: 'https://github.com/rollup/rollup',
    documentation: 'https://rollupjs.org/guide/en/',
    dependencies: [],
    tags: ['javascript', 'bundler', 'es-modules', 'tree-shaking'],
    codeExample: `// rollup.config.js\nexport default {\n  input: 'src/main.js',\n  output: {\n    file: 'bundle.js',\n    format: 'iife'\n  }\n};`
  },
  {
    name: 'Parcel',
    description: 'The zero configuration build tool',
    category: 'Build Tool',
    version: '2.10.0',
    platforms: ['windows', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 43000,
    downloads: 2100000,
    rating: 4.5,
    reviews_count: 7650,
    homepage: 'https://parceljs.org',
    repository: 'https://github.com/parcel-bundler/parcel',
    documentation: 'https://parceljs.org/docs/',
    dependencies: [],
    tags: ['javascript', 'bundler', 'zero-config', 'fast'],
    codeExample: `// package.json\n{\n  "scripts": {\n    "start": "parcel index.html",\n    "build": "parcel build index.html"\n  }\n}`
  },
  {
    name: 'esbuild',
    description: 'An extremely fast JavaScript bundler',
    category: 'Build Tool',
    version: '0.19.5',
    platforms: ['macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 37000,
    downloads: 78000000,
    rating: 4.8,
    reviews_count: 11230,
    homepage: 'https://esbuild.github.io',
    repository: 'https://github.com/evanw/esbuild',
    documentation: 'https://esbuild.github.io/api/',
    dependencies: [],
    tags: ['javascript', 'bundler', 'fast', 'go'],
    codeExample: `require('esbuild').build({\n  entryPoints: ['app.js'],\n  bundle: true,\n  outfile: 'out.js',\n}).catch(() => process.exit(1))`
  },
  {
    name: 'Babel',
    description: 'The compiler for next generation JavaScript',
    category: 'Build Tool',
    version: '7.23.2',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 43000,
    downloads: 89000000,
    rating: 4.7,
    reviews_count: 18920,
    homepage: 'https://babeljs.io',
    repository: 'https://github.com/babel/babel',
    documentation: 'https://babeljs.io/docs/en/',
    dependencies: [],
    tags: ['javascript', 'compiler', 'transpiler', 'es6'],
    codeExample: `// .babelrc\n{\n  "presets": ["@babel/preset-env", "@babel/preset-react"],\n  "plugins": ["@babel/plugin-proposal-class-properties"]\n}`
  },
  {
    name: 'TypeScript',
    description: 'TypeScript is a superset of JavaScript that compiles to clean JavaScript',
    category: 'Build Tool',
    version: '5.2.2',
    platforms: ['windows', 'macos', 'linux'],
    license: 'Apache-2.0',
    cost: 'Free',
    stars: 98000,
    downloads: 67000000,
    rating: 4.8,
    reviews_count: 28760,
    homepage: 'https://www.typescriptlang.org',
    repository: 'https://github.com/microsoft/TypeScript',
    documentation: 'https://www.typescriptlang.org/docs/',
    dependencies: [],
    tags: ['typescript', 'compiler', 'type-safe', 'microsoft'],
    codeExample: `interface User {\n  name: string;\n  age: number;\n}\n\nfunction greet(user: User): string {\n  return \`Hello, \${user.name}!\`;\n}`
  },
  {
    name: 'SWC',
    description: 'Rust-based platform for the Web',
    category: 'Build Tool',
    version: '1.3.95',
    platforms: ['windows', 'macos', 'linux'],
    license: 'Apache-2.0',
    cost: 'Free',
    stars: 30000,
    downloads: 25000000,
    rating: 4.7,
    reviews_count: 6780,
    homepage: 'https://swc.rs',
    repository: 'https://github.com/swc-project/swc',
    documentation: 'https://swc.rs/docs/getting-started',
    dependencies: [],
    tags: ['javascript', 'compiler', 'rust', 'fast'],
    codeExample: `// .swcrc\n{\n  "jsc": {\n    "parser": {\n      "syntax": "ecmascript",\n      "jsx": true\n    }\n  }\n}`
  },
  {
    name: 'Turbopack',
    description: 'The Rust-powered successor to Webpack',
    category: 'Build Tool',
    version: '0.1.0',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MPL-2.0',
    cost: 'Free',
    stars: 20000,
    downloads: 450000,
    rating: 4.6,
    reviews_count: 2340,
    homepage: 'https://turbo.build/pack',
    repository: 'https://github.com/vercel/turbo',
    documentation: 'https://turbo.build/pack/docs',
    dependencies: [],
    tags: ['javascript', 'bundler', 'rust', 'fast'],
    codeExample: `// next.config.js\nmodule.exports = {\n  experimental: {\n    appDir: true,\n  },\n}`
  },
  {
    name: 'PostCSS',
    description: 'A tool for transforming CSS with JavaScript',
    category: 'Build Tool',
    version: '8.4.31',
    platforms: ['windows', 'macos', 'linux'],
    license: 'MIT',
    cost: 'Free',
    stars: 28000,
    downloads: 25000000,
    rating: 4.7,
    reviews_count: 12340,
    homepage: 'https://postcss.org',
    repository: 'https://github.com/postcss/postcss',
    documentation: 'https://postcss.org/docs/',
    dependencies: [],
    tags: ['css', 'preprocessor', 'build', 'plugins'],
    codeExample: `// postcss.config.js\nmodule.exports = {\n  plugins: [\n    require('autoprefixer'),\n    require('cssnano')({ preset: 'default' })\n  ]\n};`
  },
];

async function seedDatabase() {
  try {
    console.log('✅ Firebase Admin initialized successfully (using JSON file)');
    console.log('🌱 Starting database seeding with 100 libraries...\n');
    
    const librariesRef = db.collection('libraries');
    
    // Clear existing data
    console.log('🗑️  Clearing existing libraries...');
    const snapshot = await librariesRef.get();
    const deletePromises = [];
    snapshot.forEach(doc => {
      deletePromises.push(doc.ref.delete());
    });
    await Promise.all(deletePromises);
    console.log(`✅ Cleared ${snapshot.size} existing libraries\n`);

    // Add libraries with timestamps
    const librariesWithTimestamps = libraries.map(lib => ({
      ...lib,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    }));

    console.log('📦 Adding libraries...\n');
    let count = 0;
    const batchSize = 10;
    
    for (let i = 0; i < librariesWithTimestamps.length; i += batchSize) {
      const batch = librariesWithTimestamps.slice(i, i + batchSize);
      const promises = batch.map(lib => librariesRef.add(lib));
      await Promise.all(promises);
      
      batch.forEach(lib => {
        count++;
        console.log(`✅ ${count}. ${lib.name} (${lib.category})`);
      });
    }

    console.log(`\n🎉 Successfully seeded ${count} libraries!`);
    
    // Display stats
    const categoryCount = {};
    librariesWithTimestamps.forEach(lib => {
      categoryCount[lib.category] = (categoryCount[lib.category] || 0) + 1;
    });
    
    console.log('\n📊 Summary by Category:');
    Object.entries(categoryCount).sort((a, b) => b[1] - a[1]).forEach(([cat, count]) => {
      console.log(`   ${cat}: ${count} libraries`);
    });

    console.log('\n✨ Database is ready to use!');
    console.log('🚀 Start your server with: npm start');
    
    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding database:', error);
    process.exit(1);
  }
}

seedDatabase();